spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:raouftakrouni0@gmail.com}
    password: ${MAIL_PASSWORD:ygcn uenj clwq hhhd}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    default-encoding: UTF-8

mediconnect:
  upload:
    image-path: ./uploads/images
  mail:
    from-name: MediConnect
    from-address: ${MAIL_USERNAME:raouftakrouni0@gmail.com}
    enabled: true
  app:
    frontend-base-url: ${FRONTEND_BASE_URL:http://localhost:4200}
