package skylinkers.tn.mediconnectbackend.entities.enums;

public enum AuditAction {

    // Auth
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGIN_2FA_REQUESTED,
    LOGIN_2FA_SUCCESS,
    LOGIN_2FA_FAILED,
    LOGOUT,

    // Registration
    SIGNUP_PATIENT,
    SIGNUP_DOCTOR,
    EMAIL_VERIFICATION_SENT,
    EMAIL_VERIFICATION_SUCCESS,
    EMAIL_VERIFICATION_FAILED,

    // Password
    PASSWORD_CHANGE_CODE_SENT,
    PASSWORD_CHANGE_CODE_VERIFIED,
    PASSWORD_CHANGE_SUCCESS,
    PASSWORD_CHANGE_FAILED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_SUCCESS,

    // 2FA — Email OTP
    TWO_FACTOR_ENABLED,
    TWO_FACTOR_DISABLED,

    // Face Recognition
    FACE_ENROLLED,
    FACE_ENROLLMENT_FAILED,
    FACE_VERIFIED,
    FACE_VERIFICATION_FAILED,
    FACE_ENABLED,
    FACE_DISABLED,
    FACE_TEMPLATE_DELETED,
    FACE_RECONFIGURED,
    FACE_FALLBACK_TO_EMAIL,

    // TOTP
    TOTP_SETUP_INITIATED,
    TOTP_SETUP_COMPLETED,
    TOTP_SETUP_CANCELLED,
    TOTP_VERIFIED,
    TOTP_VERIFICATION_FAILED,
    TOTP_DISABLED,
    TOTP_RECONFIGURED,
    RECOVERY_CODE_USED,
    RECOVERY_CODE_FAILED,
    RECOVERY_CODES_REGENERATED,

    // Multi-method MFA
    MFA_METHOD_SWITCHED,
    MFA_METHOD_EXHAUSTED,
    MFA_ALL_EXHAUSTED,
    MFA_EXHAUSTED_RESET_SUCCESS,
    MFA_EXHAUSTED_RESET_FAILED,

    // Profile
    PROFILE_VIEWED,
    PROFILE_UPDATED,
    PROFILE_PICTURE_CHANGED,

    // Admin actions on doctors
    DOCTOR_APPROVED,
    DOCTOR_REJECTED,
    DOCTOR_SUSPENDED,
    DOCTOR_REACTIVATED,

    // Admin actions on users
    USER_DEACTIVATED,
    USER_REACTIVATED,
    USER_DELETED,

    // Medical (future)
    MEDICAL_RECORD_ACCESSED,
    MEDICAL_RECORD_UPDATED,
    PRESCRIPTION_CREATED,

    // Appointment (future)
    APPOINTMENT_BOOKED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_COMPLETED,

    // System
    ADMIN_CONFIG_CHANGED,
    DATA_EXPORT_REQUESTED,

    // Legacy — kept for backward compat with existing string-based log calls
    ACCOUNT_CREATED,
    ACCOUNT_DEACTIVATED,
    ACCOUNT_ACTIVATED,
    PROFILE_UPDATE
}
